### ISSUE TITLE
Print block for multiple inputs

### ISSUE THREAD

**Issue by dube1503** [txst-per-group/Glowscript-Blocks#112]
_As a basic user , I the ability to print multiple inputs with one print statement block._

**Comment by dube1503** [comment]
![screen shot 2017-11-03 at 12 09 09 pm](https://user-images.githubusercontent.com/19582167/32386627-da72e886-c08f-11e7-8c0e-c6f0db6c061a.png)
![screen shot 2017-11-03 at 12 09 30 pm](https://user-images.githubusercontent.com/19582167/32386628-db73a1a8-c08f-11e7-83f9-666f0d8e6582.png)
Current implementation of a multi line print block.
It at the moment a block more dedicated to joining any given number of items to a string. I believe having a separate block that joins items as a string and requires being plugged into a print block can be useful but ultimately may not be completely necessary? Converting every input to a string doesnt feel necessary looking at it now as the output might create a confusing number of quotation marks, and it may be a simple method to only convert non text items to strings?
@codestar12 @hgclose

**Comment by dube1503** [comment]
![screen shot 2018-01-03 at 4 21 07 pm](https://user-images.githubusercontent.com/19582167/34542739-711b0aa0-f0a3-11e7-8666-c8851e824845.png)
![screen shot 2018-01-03 at 4 21 20 pm](https://user-images.githubusercontent.com/19582167/34542740-712fca1c-f0a3-11e7-95bc-14c268929104.png)
![screen shot 2018-01-03 at 4 21 30 pm](https://user-images.githubusercontent.com/19582167/34542741-71407088-f0a3-11e7-89a4-b8aa0a9cfcec.png)
Newest Improvements on multi inline print block
Now the blocks exists as its on print block (eliminating the need to string it onto a single print block) and it no longer converts the inputs into strings and concatenates the inputs together based on the blocks type and lets python/glowscript handle how they should print. This new version also allows for a seperate 'text_join' block (block for creating a _string_ from multiple inputs) to exist if that is still something that needs to be implemented in the future.
@codestar12 @hgclose @eah13

**Comment by eah13** [comment]
> I think the next step should be adding a default 'text' block into the mutator to follow in line with the other default blocks we have now?

That seems reasonable.  The main benefit seems to be avoiding errors from the block not having an input for each new field.  The convenience factor seems like a wash, since it would actually be less convenient if you're printing numbers or variables.  

Alternately, we could solve the error problem by making the block robust to blank inputs.  Maybe this could be inserting `''` in their place, that might be more convenient than users having to delete a bunch of default blocks when what they really want to do is print a bunch of numbers.

i.e. the block above with an additional blank argument would produce the following code 

```python
print('This = ', 0, 'and That = 1, item, '')
```

Note: I'm assuming that a blank argument to this new block would produce an error of some sort since `print(,,,)` produces a syntax error in Python.

> This new version also allows for a seperate 'text_join' block

Very cool.  This does seem to introduce an idom we ca use for a variety of `*args` functions and methods.  Let's pin specific expansions for the moment, but perhaps this rises to a design principle once we're done.

**Comment by dube1503** [comment]
Good points. I do agree that if this block is meant for addressing complicated inline statements such as printing the value of variables then forcing the user to remove and add their own blocks makes things more cumbersome than helpful. Perhaps further use might reveal otherwise, but I agree that it will most likely be better with blank default inputs. 

As for the blank arguments not producing broken code i agree that is important for keeping things running smoothly and avoiding confusing the user with more unknown errors. I tried to anticipate this and did include ```''``` wherever there was a blank input as you described, so it sounds like i made the right call on that one based on your comments.

If things are looking good then I will move forward with a PR for this issue and we can test on the dev server.

**Comment by eah13** [comment]
Great!  Sounds like a plan to me.  No default block is the option to beat, unless testing reveals a default is needed.
