### ISSUE TITLE
Math Block reset when operating on loop iterators

### ISSUE THREAD

**Issue by dube1503** [txst-per-group/Glowscript-Blocks#129]
### Reproduction Steps
 - Pull out "count with" loop block
 - Pull out "math block" and put inside loop statement
 - Create a "variable block" of the loops iterator (in this case "i") and put inside math block
 - Change "math block" operator sign (anything other than "+")
 - Click the share link button and copy shareable link
 - Paste in new tab and open trinket

### Result
The "math block" operator has reset to "+"

### Expected
The "math block" operator should remain what it was assigned

**Comment by codestar12** [comment]
@dube1503 I just read the messages on slack about the bug. I have an idea to resolve this bug. The problem is in the code that forces the variable get block to be a number its attribute this.selectedType is never set to "Number" so when mutationToDom is called it just records None. In your code for this.isIterator I think if you just add a line

```
this.selectedType = "Number"
```

it will work

**Comment by codestar12** [comment]
actually I guess I will just fix the bug since I figured it out
