### ISSUE TITLE
Type Behavior needed for 'color' types

### ISSUE THREAD

**Issue by codestar12** [txst-per-group/Glowscript-Blocks#7]
given design principle #9 all colors should be assigned with a vector type. the color palette picker should have its color changed to a vector type. The generator for color picker block should include the hex to rgb conversion and make it output a vector(r, g, b).

**Comment by dube1503** [comment]
@codestar12  Possibly change spatial vectors to read vector(x, y, z) and the color vector to read vector(r, g, b) in the drop down so that it is clear that it is a vector but it is a different kind of data in the vector, and then the block changes color to be the same color as a color block, but you still attach a vector to it.
