### ISSUE TITLE
"get" blocks for graphs do not have proper color

### ISSUE THREAD

**Issue by hgclose** [txst-per-group/Glowscript-Blocks#96]
Make a graph object. Use get block to get graph. (Yes, I know there is no reason to do this. I did it accidentally by selecting the wrong thing in the 'get' pull down menu.) The color of the graph get block will be the same as the last color that was deliberately applied to the block according to its data type. This color could be a shape color, or vector, or number, or string - and it might communicate to the user that the graph block can do what its color would suggest. In order to communicate clearly to the user that the get graph block cannot do these things, let's have the block take on the graph color as a way to tell the user that they made the wrong selection in the menu, and they need to go back and select the correct thing.

**Comment by dube1503** [comment]
This seems to be an oversight as we purposefully have the get block not react to a graph selection in the sense that you cant store the graph attributes to a variable because there doesnt seem a simple use case for this (if the user wishes to change any graph settings they can more easily just readjust the original graph block). 
However I was unaware of the bug of color not changing so I agree that just having the color change would be helpful and simple way to communicate to the users even if access to the graph attributes were not available.
