### ISSUE TITLE
'make trail' data resets when a shape block is reset

### ISSUE THREAD

**Issue by hgclose** [txst-per-group/Glowscript-Blocks#98]
Start a new shape block. Add 'make trail' to the attributes. Change the data in 'make trail', like changing the trail type or interval. Change the attributes (add or subtract some) on the shape with the gear box menu to refresh the block. The data in make trail has reset to default.

**Comment by dube1503** [comment]
@codestar12 I am a little weary about trying to push any changes for this issue as it may directly conflict with your mutator saved connections fixes that you are working on and also your fix may be able to relate to this issue as well?

**Comment by dube1503** [comment]
@codestar12 @hgclose another note we did not discuss. If the make trail attribute had block inputs in the style of all the other attribute types then it would reflect the same procedure and would fix this issue as a side effect because they blocks already save "block connections" but do not store or reconnect values
